version: '3'
services:
    react:
      container_name: reactApp
      build: . 
      ports:
        - "3001:3001"
        - "3000:3000"
      env_file:
        - ./.env

      stdin_open: true
      tty: true 

